version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 100
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 100
    commit-message:
      prefix: chore
      include: scope

