when@dev: &dev
    nelmio_alice:
        functions_blacklist:
            - 'current'
            - 'shuffle'
            - 'date'
            - 'time'
            - 'file'
            - 'md5'
            - 'sha1'

when@test: *dev
