---
#- name: Laravel | Clone
#  become: no
#  git:
#    repo: "https://github.com/Grafikart/Grafikart.fr.git"
#    dest: "{{ root_path }}"
#    version: main
- name: Laravel | Scheduler
  become: no
  cron:
    name: "{{ domain }} scheduler"
    job: "cd {{ root_path }} && php artisan schedule:run >> /dev/null 2>&1"
- name: Laravel | Queue Service
  become: no
  template:
    src: "queue.service.j2"
    dest: "~/.config/systemd/user/queue.service"
- name: Laravel | Queue Service activation
  become: no
  systemd:
    scope: user
    state: started
    daemon_reload: yes
    enabled: yes
    name: "queue"
- name: Laravel | Logrotate"
  template:
    src: logrotate.j2
    dest: "/etc/logrotate.d/{{ domain }}"
- name: Laravel | Caddy configuration
  become: true
  template:
    src: caddyfile.j2
    dest: "/etc/frankenphp/Caddyfile.d/{{ domain }}.caddyfile"
