<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250815084512 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE podcast DROP CONSTRAINT fk_d7e805bdf675f31b');
        $this->addSql('ALTER TABLE podcast_user DROP CONSTRAINT fk_66b74805786136ab');
        $this->addSql('ALTER TABLE podcast_user DROP CONSTRAINT fk_66b74805a76ed395');
        $this->addSql('ALTER TABLE podcast_vote DROP CONSTRAINT fk_b1341b28ebb4b8ad');
        $this->addSql('ALTER TABLE podcast_vote DROP CONSTRAINT fk_b1341b28786136ab');
        $this->addSql('DROP TABLE podcast');
        $this->addSql('DROP TABLE podcast_user');
        $this->addSql('DROP TABLE podcast_vote');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE podcast (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, author_id INT NOT NULL, title VARCHAR(255) NOT NULL, content TEXT DEFAULT NULL, votes_count INT DEFAULT 0 NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, duration INT DEFAULT 0 NOT NULL, youtube VARCHAR(255) DEFAULT NULL, mp3 VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_d7e805bdf675f31b ON podcast (author_id)');
        $this->addSql('CREATE TABLE podcast_user (podcast_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (podcast_id, user_id))');
        $this->addSql('CREATE INDEX idx_66b74805786136ab ON podcast_user (podcast_id)');
        $this->addSql('CREATE INDEX idx_66b74805a76ed395 ON podcast_user (user_id)');
        $this->addSql('CREATE TABLE podcast_vote (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, podcast_id INT NOT NULL, voter_id INT NOT NULL, weight DOUBLE PRECISION DEFAULT \'1\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_b1341b28ebb4b8ad ON podcast_vote (voter_id)');
        $this->addSql('CREATE INDEX idx_b1341b28786136ab ON podcast_vote (podcast_id)');
        $this->addSql('ALTER TABLE podcast ADD CONSTRAINT fk_d7e805bdf675f31b FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE podcast_user ADD CONSTRAINT fk_66b74805786136ab FOREIGN KEY (podcast_id) REFERENCES podcast (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE podcast_user ADD CONSTRAINT fk_66b74805a76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE podcast_vote ADD CONSTRAINT fk_b1341b28ebb4b8ad FOREIGN KEY (voter_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE podcast_vote ADD CONSTRAINT fk_b1341b28786136ab FOREIGN KEY (podcast_id) REFERENCES podcast (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
