name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: write

jobs:
  php-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          tools: composer:v2
      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: Create key
        run: php artisan key:generate
      - name: Tests
        run: php artisan test --compact
  front-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install frontend dependencies
        run: bun install
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          tools: composer:v2
      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: Wayfinder
        run: php artisan wayfinder:generate --with-form
      - name: Test
        run: bun run test --run
